// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKKUqKfkHy17f9y_yLZn2I9BEhuNEZSno',
    appId: '1:442989875921:web:88df5cd8ffe72a90e2abf0',
    messagingSenderId: '442989875921',
    projectId: 'login-96df6',
    authDomain: 'login-96df6.firebaseapp.com',
    storageBucket: 'login-96df6.appspot.com',
    measurementId: 'G-SJY0ZEF8Q3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7znLxihnirZmMeoWUgsfFxC7ZLyyYkY4',
    appId: '1:442989875921:android:d03ddc631fd3a9a0e2abf0',
    messagingSenderId: '442989875921',
    projectId: 'login-96df6',
    storageBucket: 'login-96df6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqSl8doNEy9qmk-mtdF2fKiSak81ul5To',
    appId: '1:442989875921:ios:691c2c2f8d2910f0e2abf0',
    messagingSenderId: '442989875921',
    projectId: 'login-96df6',
    storageBucket: 'login-96df6.appspot.com',
    iosBundleId: 'com.example.loginPpb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqSl8doNEy9qmk-mtdF2fKiSak81ul5To',
    appId: '1:442989875921:ios:691c2c2f8d2910f0e2abf0',
    messagingSenderId: '442989875921',
    projectId: 'login-96df6',
    storageBucket: 'login-96df6.appspot.com',
    iosBundleId: 'com.example.loginPpb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKKUqKfkHy17f9y_yLZn2I9BEhuNEZSno',
    appId: '1:442989875921:web:f4391b5b73b7dc3be2abf0',
    messagingSenderId: '442989875921',
    projectId: 'login-96df6',
    authDomain: 'login-96df6.firebaseapp.com',
    storageBucket: 'login-96df6.appspot.com',
    measurementId: 'G-7KDZ9TQY3X',
  );

}